### ISSUE TITLE
Could you provide spoof datas?

### ISSUE THREAD

**Issue by tycallen** [IDRnD/LCC_FASD#1]
Why only real images.

**Comment by tycallen** [comment]
And the real images size is 800+ G? I'm wondering how many frames in it.

**Comment by xsacha** [comment]
The research paper contains the link to the cropped (margin=0.25) real and spoof images. It is 4.8GB.

This dataset is 800+GB because it has the full frame for every image.

**Comment by tycallen** [comment]
> The research paper contains the link to the cropped (margin=0.25) real and spoof images. It is 4.8GB.
> 
> This dataset is 800+GB because it has the full frame for every image.

Thanks for your reply, I file this issue because I can't open the link in the paper. Today I check it again and find out when I copy the address, the new line character is also copied to browser so I can't open it before.

Thank you for sharing.
